import {Geist} from "next/font/google";


const geist = Geist({subsets: ["latin"],
  weight: '100'})


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geist.className}> 
        {children}
      
      </body>
    </html>
  );
}
